services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Synolia\SyliusGDPRPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,SynoliaSyliusGDPRPlugin.php}'

    Synolia\SyliusGDPRPlugin\Menu\GDPRMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addGDPRMenuItems }
